# Tacet Grammar (Go-Style EBNF)

program
    = { line } EOF
    ;

line
    = [ seq ] EOL [ block ]
    ;

block
    = INDENT { line } DEDENT
    ;

seq
    = expr { [ _ ] COMMA [ _ ] expr }
    ;

expr
    = infix { _ TAG }
    ;

infix
    = apply { _ OPER [ _ apply ] }
    ;

apply
    = tight { _ tight }
    ;

tight
    = [ OPER ] atom { OPER atom } [ OPER ]
    ;

atom
    = TYPE_ID
    | NAME_ID
    | NUM
    | STR
    | CHR
    | tacet
    | oper_id
    | group
    ;

tacet
    = TACET _ TAG
    ;

oper_id
    = L_PAR OPER R_PAR
    | L_BRA OPER R_BRA
    | L_CUR OPER R_CUR
    ;

group
    = L_PAR inner R_PAR
    | L_BRA inner R_BRA
    | L_CUR inner R_CUR
    ;

inner
    = [ _ ] [ seq [ _ ] ]
    | EOL block
    ;
